### ISSUE TITLE
Schema dati

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#1]
Sera! Ecco un esempio di schema dati per i file del repo:

### Struttura file `incidenza-YYYYMMDD.csv`, `incidenza-latest.csv`, `incidenza.csv`

Campo | Descrizione | Formato | Esempio
-- | -- | -- | --
data | Data pubblicazione report DASOE | YYYY-MM-DD | 2021-10-27
cod_prov | Codice ISTAT della Provincia | Numero | 84
pro_com_t | Codice ISTAT del Comune | Numero | 084002
provincia | Denominazione della Provincia | Testo | Agrigento
comune | Denominazione del Comune | Testo | Alessandria della Rocca
incidenza | Incidenza cumulativa settimanale (ogni 100.000 abitanti) | Numero | 855
casi | Nuovi casi settimanali | Numero | 6

### Struttura file `vaccini-YYYYMMDD.csv`, `vaccini-latest.csv`, `vaccini.csv`

Campo | Descrizione | Formato | Esempio
-- | -- | -- | --
data | Data pubblicazione report DASOE | YYYY-MM-DD | 2021-10-27
cod_prov | Codice ISTAT della Provincia | Numero | 84
pro_com_t | Codice ISTAT del Comune | Numero | 084002
provincia | Denominazione della Provincia | Testo | Agrigento
comune | Denominazione del Comune | Testo | Alessandria della Rocca
%vaccinati | Percentuale di persone vaccinate con almeno una dose (calcolata rispetto al target) | Numero | 84.65
%immunizzati | Percentuale di: persone vaccinate con 2 o più dosi, persone vaccinate in monodose per pregressa infezione Covid, persone vaccinate con Janssen (calcolata rispetto al target) | Numero | 82.72

Volendo, potremmo eliminare qualsiasi riferimento alla provincia e mantenere solo il codice istat del comune ma non so se ha senso.

Che ne dite?

**Comment by gabacode** [comment]
1. Specificherei che si tratta di incidenza cumulativa su 100.000 abitanti, se si vuole usare il dato che riceviamo.
2. Proposta: chiamare le colonne direttamente `vaccinati` ed `immunizzati` ?
3. Assicurarci che il target sia la popolazone ISTAT (mese?) 2021 >= 12 o, in caso contrario, omettere il campo.
4. Il codice provincia, o il nome possono essere utili qualora si voglia fare una [query per provincia](https://covid-reports-api.herokuapp.com/vaccini?&q=Palermo) direttamente dalle API.

Per il resto mi sembra ottimo ed in linea con quello che abbiamo e possiamo costruire :)

**Comment by dennisangemi** [comment]
Grazie gab

1. Sono d'accordo, modifico subito
2. Per me andrebbe bene, sentiamo pure il parere di qualcun'altro (cc. @aborruso  @gbvitrano )
3. Non appena posso preparo mail da inviare a DASOE ma temo che la risposta, se arriverà, arriverà tra un bel po' di giorni. Omettiamo il campo? Se qualcuno vuole stimare il valore assoluto di vaccinati può comunque utilizzare un'altro file (che carichiamo in seguito) e fare un join 
4. oki, lasciamolo (pensavo fosse inutile)

**Comment by dennisangemi** [comment]
Aggiornamenti sul punto 3: il target varia nel tempo (e non sappiamo di quanto a meno che non siano loro a pubblicarlo), [qui la prova](https://docs.google.com/spreadsheets/d/1wWD7jsk5WdimK88BcyT6GpRaJd-ulRs_0eRo2MQBTfQ/edit?usp=sharing). A questo punto siamo costretti ad omettere il campo perchè il valore di cui siamo in possesso non è corretto cioè non aggiornato (anche se si tratta comunque di piccole variazioni)

**Comment by dennisangemi** [comment]
Ho rimosso il campo `target `per i motivi sorpa citati e rinominato i campi dei vaccinati e degli immunizzati in `%vaccinati` `%immunizzati`
