### ISSUE TITLE
Lancio

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#10]
Preparare blog post e qualche tweet per far conoscere il nostro progetto e per chiedere alla Regione (per l'ennesima volta) la pubblicazione di dati aperti
![covid-open-report-sicilia](https://user-images.githubusercontent.com/77018886/143773903-3a391519-e513-495e-adcd-9d6f3544c577.png)

**Comment by gabacode** [comment]
Ho iniziato a scrivere questo come potenziale nuovo blog post:
<del>https://docs.google.com/document/d/1ao97Oo8u29587WqiSnrk6TBAba4hUCV8dOSe4JUF07k/edit</del>
edit: aggiunta bozza post sul blog

**Comment by dennisangemi** [comment]
Ciao @gabacode, forse sarebbe più azzeccato un titolo del tipo: "Da PDF ad API: come abbiamo liberato i dati covid comunali" ?

Vero è che stiamo liberando i "dati sui vaccini" ma secondo me non dobbiamo dimenticare anche i dati sui contagi (e incidenza) che prima non esistevano ;)

**Comment by aborruso** [comment]
Ciao @gabacode, 
ho messo qualche nota.

Pubblicherei anche il 27.

**Comment by aborruso** [comment]
Azz, ho visto solo ora che in bozza. Vabbé, buttaci un occhio su docs per favore

**Comment by gabacode** [comment]
Grazie @aborruso ! Aggiungo alla bozza su wp

**Comment by dennisangemi** [comment]
@gabacode nel blog post che uscirà ha senso segnalare gli errori #13 e #14 ?

**Comment by gabacode** [comment]
> @gabacode nel blog post che uscirà ha senso segnalare gli errori #13 e #14 ?

@dennisangemi 
Secondo me il lavoro che stiamo facendo va al di là di eventuali errori che abbiamo trovato, e (potenzialmente) troveremo all'interno dei bollettini rilasciati in PDF. Dovremmo però segnalarlo all'Ente per richiedere piu delucidazioni a riguardo, e piu attenzione per i bollettini futuri.

**Comment by dennisangemi** [comment]
Hai ragione! Sfrutterei però ancora una volta il blog post per chiedere un "canale di comunicazione diretto" che ci permetta di dialogare con la Regione. E credo che questo sia presente nella bozza (insieme alle mail prive di risposta)

**Comment by gabacode** [comment]
Il post e' stato [pubblicato](https://opendatasicilia.it/2021/12/31/da-pdf-ad-api-come-abbiamo-liberato-i-dati-covid-comunali/).
