### ISSUE TITLE
Modifica al target

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#11]
Come ci comportiamo adesso che abbiamo ricevuto conferma che il target sul quale viene calcolata la percentuale di vaccinati e immunizzati è rappresentato dalla popolazione >= 5? Qualche idea? Bisogna modificare lo schema dati?

### task

- [x] aggiungere specifica target >= 5 in readme

Io ci penso un po' e scrivo qualcosa qui

**Comment by gabacode** [comment]
Io sarei per il "ribilanciamento" retrospettivo delle percentuali nei files passati.

**Comment by dennisangemi** [comment]
Per adesso stiamo pubblicando le percentuali così come sono presenti nei bollettini pdf.
Aggiungo dettagli nel README.
Qualora dovessero esserci idee migliori, riapriamo issue e decidiamo il da farsi.
