### ISSUE TITLE
Variazione allegato 2

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#12]
Ciao @gabacode, mi confermi che hai risolto il problema della conversione del nuovo allegato?

**Comment by gabacode** [comment]
> Ciao @gabacode, mi confermi che hai risolto il problema della conversione del nuovo allegato?

Si, via 0d37943eb943e7c818f18d68076a9de2605c05ff

**Comment by dennisangemi** [comment]
Grazie
