### ISSUE TITLE
feature request: URL di front-end parametrizzabile

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/covid-open-report-sicilia#15]
Mi piacerebbe che fosse possibile avere un URL di front-end <https://report-dasoe.opendatasicilia.it/COD_ISTAT> per avere una pagina che carica le infografiche di quel comune e non sempre quelle di Aci Castello.

Grazie

**Comment by gabacode** [comment]
Avevamo aggiunto l'opzione di ricerca per `slug` con un URL, ad esempio: https://report-dasoe.opendatasicilia.it/comune/palermo  
Ho appena [aggiunto](https://github.com/opendatasicilia/cors-dashboard/commit/da5b8532dc49ebb9bd205a3491504299fb5ff623) la possibilità di cercare anche via codice ISTAT, esempio: https://report-dasoe.opendatasicilia.it/comune/082053

ps. teoricamente ad ogni refresh, se non specificato, dovrebbe selezionare un comune casuale

**Comment by aborruso** [comment]
> Avevamo aggiunto l'opzione di ricerca per `slug` con un URL, ad esempio: https://report-dasoe.opendatasicilia.it/comune/palermo
> Ho appena [aggiunto](https://github.com/opendatasicilia/cors-dashboard/commit/da5b8532dc49ebb9bd205a3491504299fb5ff623) la possibilità di cercare anche via codice ISTAT, esempio: https://report-dasoe.opendatasicilia.it/comune/082053

Andava bene anche quello che c'era già allora :(
Scusatemi.

Ma dove lo trovavo scritto?

Scusate ancora

**Comment by gabacode** [comment]
@aborruso E' un'ottima idea cercare anche via codice ISTAT, grazie! - L'avevo aggiunto al readme, ma solo un'oretta fa

**Comment by aborruso** [comment]
> @aborruso E' un'ottima idea cercare anche via codice ISTAT, grazie! - L'avevo aggiunto al readme, ma solo un'oretta fa

Ah ok, non sono pazzo.

Grazie
