### ISSUE TITLE
schema dati in yaml

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#16]
Ciao @aborruso, mi piacerebbe farti un paio di domande e la scrivo qui perchè magari può tornare utile a qualcun altro:
- quanto è importante avere uno schema dati in formato `yaml` (come quello che hai preparato per [informacovid](https://github.com/opendatasicilia/informa-covid19/blob/main/dati/informacovid/informacovid_schema.yaml)) ? 
- Secondo te è opportuno che io ne inserisca uno simile anche in questo repo? 
- Si potrebbe completare con informazioni relative all'encoding o al separatore di campo?
- Quale sarebbe l'optimum?

**Comment by aborruso** [comment]
> quanto è importante avere uno schema dati in formato yaml (come quello che hai preparato per informacovid) ?

Ciao @dennisangemi avere un "dizionario" standard che descrive i dati è cosa preziosa, per almeno queste ragioni:

- rendi i dati machine readable in pienezza e certezza;
- puoi creare verifiche automatiche sui dati (come in informacovid)
- rendi le informazioni interoperabili.

Ho usato la descrizione di tipo [frictionless](https://specs.frictionlessdata.io/table-schema/#types-and-formats).

Ne stiamo scrivendo in una [guida ancora in costruzione](https://ondata.github.io/guidaPraticaPubblicazioneCSV/guida/dizionario_dati/), dove si cita uno standard, ancora più standard: https://www.w3.org/TR/tabular-metadata/

> - Secondo te è opportuno che io ne inserisca uno simile anche in questo repo?

Tra le altre cose, facendolo, si fa cultura e si impara. Per me è buona cosa

> - Si potrebbe completare con informazioni relative all'encoding o al separatore di campo?

Certo, è essenziale. E lo standard frictionless lo prevede.

> - Quale sarebbe l'optimum?

Non lo so. Io mi rendo disponibile a creare la prima versione e lascio poi a te eventuali estensioni, correzioni e aggiornamenti.

Non appena c'è uno schema di massima "pronto", intendo dire anche soltanto un CSV o JSON "finale", fammi un fischio.

**Comment by dennisangemi** [comment]
Quante belle informazioni! Grazie mille Andrea.

- in questo repo mancano i file yaml ma c'è la documentazione per le API che ha preparato @gabacode. Se tu sei d'accordo, possiamo aggiungere i file yaml anche qui (lo schema è fissato e non credo che cambierà - almeno per adesso)
- nel [repo ordinanze-covid](https://github.com/opendatasicilia/ordinanze-covid) ho aggiunto un file yaml sfruttando quello che avevi preparato per informacovid. Lo schema, anche in questo caso, dovrebbe essere definitivo e interesserebbe solo i file data.csv e data.json. lemme know se è sufficiente o sarebbe meglio inserire ulteriori dettagli ;)

**Comment by dennisangemi** [comment]
Aggiungo una domanda: meglio yaml o json?

Edit:
Frictionless funziona senza problemi sia con uno che con l'altro quindi credo non ci siano differenze

**Comment by dennisangemi** [comment]
Ciao @gabacode, secondo te avrebbe senso sostituire il file attualmente chiamato `package.json` con il file `datapackage.json` (o yaml) secondo gli standard [frictionless](https://specs.frictionlessdata.io/data-package/#introduction)? Nel datapackage.json si possono comunque inserire le info relative ai [contributors ](https://specs.frictionlessdata.io/data-package/#contributors)e alla [licenza](https://specs.frictionlessdata.io/data-package/#licenses)

**Comment by dennisangemi** [comment]
Come è possibile notare dalle references precedenti:
- Ho aggiunto i metadati dei file `vaccini.csv` e `incidenza.csv` e si trovano nel file [`datapackage.yaml`](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/datapackage.yaml). (Bisognerebbe aggiungere la licenza e i contibutors se si vuole eliminare il package.json)
- Ho aggiunto la [action di frictionless](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/.github/workflows/frictionless.yaml) che valida i dati ad ogni push nella cartella `dati` e mostra un badge nel [README](https://github.com/opendatasicilia/covid-open-report-sicilia#readme) - se è verde, vuol dire che è tutto ok ;). Spero di non aver fatto [errori ](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/a5dc89fd3e812105b308da2473574cf3631bc293/.github/workflows/frictionless.yaml#L8)e che la action venga azionata veramente ad ogni push nella cartella dati

**Comment by gabacode** [comment]
Ottimo lavoro @dennisangemi, Grazie!
Il file `package.json` è necessario per il corretto funzionamento dell'app node (le API).
Lo schema è definito in formato YAML all'interno di un commento JSDoc per la documentazione, ad esempio [qui ](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/api/routes/incidenza.js#L11-L32), e per il csv parser ad esempio [qui](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/api/routes/incidenza.js#L115-L123), quindi dovremmo essere abbastanza "tranquilli" tenendo entrambi i files.

**Comment by dennisangemi** [comment]
D'accordo allora teniamoli entrambi!

**Comment by dennisangemi** [comment]
Dimenticavo: non chiudo senza la benedizione di @aborruso che valida la validazione ;)

**Comment by aborruso** [comment]
Mi pare ottimo @dennisangemi !

Che te ne sta sembrando di frictionless?

**Comment by dennisangemi** [comment]
> Che te ne sta sembrando di frictionless?

@aborruso mi sta piacendo tantissimo! Sono un po' intimorito dalla vastità del progetto che non ho ancora compreso benissimo però la documentazione e le guide che ho trovato mi sono sembrate molto chiare (se ci sono riuscito io senza romperti le scatole vuol dire che sono fatte davvero bene lol)
