### ISSUE TITLE
Immunizzati cambia etichetta

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#17]
Nel bollettino settimanale PDF, il campo che si chiamava "Immunizzati" adesso è "% con ciclo primario completato" ed in effetti ha più senso (dato il vaccino non rende immuni lol ;) - come qualcuno faceva notare)

Come ci comportiamo? Da noi c'è ancora il campo "immunizzati" ma l'abbiamo definito in modo tale che sia concettualmente uguale a "% con ciclo primario completato". Lasciamo tutto così com'è o modifichiamo nome campo? È lecito modificare il nome del campo?

cc @aborruso

**Comment by aborruso** [comment]
> È lecito modificare il nome del campo?

Il nome campo è semanticamente sbagliato. Ma credo che sia ben descritto.

Lo cambierei; se fa da input verso qualche sistema, va comunicato e concordato. E va scritto in un file di log

Baci

**Comment by gbvitrano** [comment]
> Nel bollettino settimanale PDF, il campo che si chiamava "Immunizzati" adesso è "% con ciclo primario completato" ed in effetti ha più senso (dato il vaccino non rende immuni lol ;) - come qualcuno faceva notare)
> 
> Come ci comportiamo? Da noi c'è ancora il campo "immunizzati" ma l'abbiamo definito in modo tale che sia concettualmente uguale a "% con ciclo primario completato". Lasciamo tutto così com'è o modifichiamo nome campo? È lecito modificare il nome del campo?
> 
> cc @aborruso

Era ora... meglio tardi che mai :-) :-) 
Ora mi tocca sistemare la dashboard  :-) :-)

**Comment by gabacode** [comment]
Appena abbiamo in mente il nuovo nome del campo stabiliamo una data e allochiamo un'oretta di tempo in cui aggiorniamo i campi ovunque riferiti precedentemente.

All'interno di questo repo:
- datapackage.yaml
- README.md
- api/routes/vaccini.js
- data/vaccini/*.csv
- scripts/convert.py

**Comment by dennisangemi** [comment]
> E va scritto in un file di log

Ciao @aborruso  (e grazie) andrebbe bene un CHANGELOG.md come [questo ](https://github.com/pcm-dpc/COVID-19/blob/master/CHANGELOG.md) ? Mi consigli una base da cui partire? thx

**Comment by dennisangemi** [comment]
### Proposte per rinominare i field `%vaccinati` e `%immunizzati`:
- `%vaccinati` > `%prima_dose`
- `%immunizzati` > `%seconda_dose`

Idee migliori? (ovviamente documentiamo tutto e inseriamo le precisazioni sul monodose Janssen ecc.)

**Comment by dennisangemi** [comment]
> Appena abbiamo in mente il nuovo nome del campo stabiliamo una data e allochiamo un'oretta di tempo in cui aggiorniamo i campi ovunque riferiti precedentemente.
> 
> All'interno di questo repo:
> 
> * datapackage.yaml
> * README.md
> * api/routes/vaccini.js
> * data/vaccini/*.csv
> * scripts/convert.py

Ciao @gabacode  io potrei occuparmi di:
- datapackage.yaml
- README.md
- data/vaccini/*.csv

Ti potresti occupare del resto?

**Comment by gabacode** [comment]
> Ti potresti occupare del resto?

Va bene, appena siamo tutti d'accordo partiamo!

**Comment by aborruso** [comment]
> Ciao @aborruso (e grazie) andrebbe bene un CHANGELOG.md come [questo ](https://github.com/pcm-dpc/COVID-19/blob/master/CHANGELOG.md) ? Mi consigli una base da cui partire? thx

Sì, una descrizione iniziale, e un dot point per ogni data di release

**Comment by dennisangemi** [comment]
> Sì, una descrizione iniziale, e un dot point per ogni data di release

Grazie mille @aborruso .

Se siamo tutti/e d'accordo, domani io e @gabacode ci occuperemo di rinominare i campi come di seguito indicato:
- `%vaccinati` > `%prima_dose`
- `%immunizzati` > `%seconda_dose`

**Comment by dennisangemi** [comment]
Dovremmo aver finito! Ci perdonerete se all'ultimo abbiamo deciso di non utilizzare il '%' nel nome del campo senza comunicarvelo ;)

Io farei chiudere @gabacode così mi lavo le mani ihihi

**Comment by gabacode** [comment]
Chiudo

**Comment by pigreco** [comment]
> Ci perdonerete se all'ultimo abbiamo deciso di non utilizzare il '%' nel nome del campo senza comunicarvelo

GRAVISSIMO :-)

**Comment by aborruso** [comment]
Ho aggiunto nel readme una nota sul changelog

![image](https://user-images.githubusercontent.com/30607/149892017-e3fdf282-4122-48fa-9163-fdeed53cb857.png)

**Comment by dennisangemi** [comment]
Grazie @aborruso
