### ISSUE TITLE
Lunghezza lista dei bollettini pubblicati sul readme

### ISSUE THREAD

**Issue by gabacode** [opendatasicilia/covid-open-report-sicilia#22]
Siamo arrivati al bollettino n.25, la lista dei bollettini sul [readme](https://github.com/opendatasicilia/covid-open-report-sicilia#readme) va crescendo e potrebbe alla lunga diventare "scomoda" ed esteticamente non troppo piacevole.

Mettiamo la lista dentro un dropdown, tipo [così](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61#file-dropdown-md)? Che ne pensate?

**Comment by dennisangemi** [comment]
Non sapevo fosse possibile farlo! Per me è assolutamente sì. Grazie mille gab

**Comment by gabacode** [comment]
Anch'io l'ho scoperto oggi! Ho dovuto però modificare la lista e renderla in html altrimenti non la prendeva dentro al tag `<summary>`

**Comment by dennisangemi** [comment]
Perfetto, grazie mille. Sarebbe necessario modificare anche lo script che "appende" i link ?

**Comment by gabacode** [comment]
Si, esatto. Lo modifico successivamente. Per ora chiudo.

**Comment by dennisangemi** [comment]
Grazie!

**Comment by gabacode** [comment]
> Si, esatto. Lo modifico successivamente. Per ora chiudo.

Aggiornato in 4627a4c

**Comment by dennisangemi** [comment]
> > Si, esatto. Lo modifico successivamente. Per ora chiudo.
> 
> Aggiornato in [4627a4c](https://github.com/opendatasicilia/covid-open-report-sicilia/commit/4627a4c5da77aaf37a6c4e2031ad13ce20b6afa8)

Grazie gab!
