### ISSUE TITLE
Nome file pdf

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#8]
Buon pomeriggio, secondo voi dovremmo [pubblicare i pdf](https://github.com/opendatasicilia/covid-open-report-sicilia/tree/main/download) rinominandoli con un pattern standard oppure mantenendo il nome dei pdf pubblicati dalla regione? (Attualmente si sta mantenendo il nome originario)

**Comment by aborruso** [comment]
Caro Dennis,
da qualche parte salverei una risorsa (anche un CSV) con almeno due
attributi: nome file (un nome normalizzato che piace a te/noi) e URL
originario.

E a quel punto i file si chiameranno come colonna 1.

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il ven 12 nov 2021, 13:55 Dennis Angemi ***@***.***> ha
scritto:

**Comment by dennisangemi** [comment]
fatto https://github.com/opendatasicilia/covid-open-report-sicilia/commit/10f5d4760d8f9dba72d7eaa170cce4ad15c9cd4f ! Grazie mille. Posso chiudere?
