### ISSUE TITLE
Automatismo

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/covid-open-report-sicilia#9]
Di seguito alcune idee per la realizzazione dell'automatismo. Non abbiamo nessuna fretta e soprattuto non sentiamo la necessità impellente di realizzarlo perchè potremmo continuare ad aggiornare manualmente i file di questo repo una volta alla settimana

**Github Action** 

- **Trigger**: feed RSS che notifica solo i pdf (grazie @aborruso e grazie @gaba)
- Scaricare PDF, rinominarlo in `report-YYYYMMDD` e caricarlo nella cartella [`download`](https://github.com/opendatasicilia/covid-open-report-sicilia/tree/main/download);
- Convertire l'Allegato 1 e l'Allegato 2 in CSV secondo lo schema concordato e aggiornare i file:
    - `vaccini.csv` (aggiungere le nuove righe);
    - `vaccini-latest.csv` (sostituire con nuovo file);
    - `vaccini-YYYYMMDD.csv` (creare nuovo file);
    - `incidenza.csv` (aggiungere nuove righe);
    - `incidenza-latest.csv` (sostituire con nuovo file);
    - `incidenza-YYYYMMDD.csv` (creare nuovo file);
    - `report.csv` (aggiungere riga);
- Se possibile: aggiungere alla sezione *[Bollettini pubblicati del `README`](https://github.com/opendatasicilia/covid-open-report-sicilia#bollettini-pubblicati)* il link al nuovo pdf

**Comment by gabacode** [comment]
Ho iniziato a dare un'occhiata alle GitHub Actions ed è veramente un mondo fantastico!
Una run su [questo repo temporaneo](https://github.com/gabacode/dasoe_updates) ha dato buoni risultati, i files sono stati [aggiornati](https://github.com/gabacode/dasoe_updates/commit/d2f0bdeb1d9c544f4ae69155e0b08e0bd7b1858a) automaticamente.

Alcune riflessioni sull'utilizzo dell'[action](https://github.com/gabacode/dasoe_updates/blob/main/.github/workflows/main.yml).

1 - Aggiornare i files tramite action è piu semplice se gli scripts si trovano [all'interno del repository](https://github.com/gabacode/dasoe_updates/tree/main/scripts). A meno che non si voglia fare un curl/wget da url esterno, ma aggiunge uno step e un livello di fallimento in piu.

2 - Gli script sono fatti su misura per l'occasione, e potrebbero rompersi qualora gli standard di pubblicazione da parte dell'Ente cambino drasticamente.

3 - Sostenibilità: ho cercato di dividere l'action in 2 step l'uno dipendente dall'altro, così che ad esempio si possa scaricare la Java JDK (requisito per tabula) solo nel momento in cui il primo step abbia esito positivo. Per me sono un pò risorse sprecate, non ho capito bene se usano layers con cache o ad ogni run bisogna installare tutto (ok paga GitHub ma fa sempre un pò strano)

  - Problema 1: [Non sempre](https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/) il cron schedule si innesca automaticamente, forse sarebbe meglio fetchare l'RSS con un servizio esterno e mandare lo start dell'action via IFTTT o altro?

  - Problema 2: Quando non ci sono nuovi PDF da scaricare mando un exit(1) da Python. Questo però [fa fallire l'intero job](https://github.com/gabacode/dasoe_updates/runs/4415812921?check_suite_focus=true#step:5:7), e manda notifica via email. Esiste un modo di terminare lo step in maniera piu graziosa? Ho provato con environment variables ma essendo python un processo fork non escono dallo script. Anche `if: failed()` termina il workflow in maniera scorbutica. Probabilmente qualche magia in bash potrebbe risolvere il problema? :)

- Alternativa eco-friendly: Fetchare e convertire i files da un server esterno (come già succede col [bot telegram](https://github.com/gabacode/vaxExtract), che eventualmente manda un push al repo tramite deploy keys (ma potrebbe essere discutibile a livello di sicurezza). Ma sarebbe davvero eco-friendly? Quanto potrebbe impattare ad esempio confrontando l'installazione di tutte le dipendenze da una singola action ogni n minuti (con JAVA e quant'altro), invece?

Ad ogni modo, credo che questa settimana potremmo provarlo, è attivo sul [repo di prova](https://github.com/gabacode/dasoe_updates/actions).

Che ne pensate? @dennisangemi @aborruso

**Comment by aborruso** [comment]
Caro @gabacode ,
uso le actions per fare gitscraping da tempo: non sono la soluzione a tutto, ma di consentono di fare bene e senza grandi sforzi tantissime cose.

Vado per punti


> 1 - Aggiornare i files tramite action è piu semplice se gli scripts si trovano [all'interno del repository](https://github.com/gabacode/dasoe_updates/tree/main/scripts). A meno che non si voglia fare un curl/wget da url esterno, ma aggiunge uno step e un livello di fallimento in piu.

Io faccio sempre così. Tutti gli script possono fallire, l'importante è fare in modo almeno di saperlo.

> 2 - Gli script sono fatti su misura per l'occasione, e potrebbero rompersi qualora gli standard di pubblicazione da parte dell'Ente cambino drasticamente.

Non credo valga la pena di costruire un algoritmo di machine learning che si autoadatta :)

Insomma, anche qui, l'unica è gestire l'errore e farsi avvisare e/o bloccare eventuali update, in modo che rimanga sempre l'ultima versione "verificata".

> 3 - Sostenibilità: ho cercato di dividere l'action in 2 step l'uno dipendente dall'altro, così che ad esempio si possa scaricare la Java JDK (requisito per tabula) solo nel momento in cui il primo step abbia esito positivo. Per me sono un pò risorse sprecate, non ho capito bene se usano layers con cache o ad ogni run bisogna installare tutto (ok paga GitHub ma fa sempre un pò strano)
> 
> * Problema 1: [Non sempre](https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/) il cron schedule si innesca automaticamente, forse sarebbe meglio fetchare l'RSS con un servizio esterno e mandare lo start dell'action via IFTTT o altro?

Nella mia esperienza è molto raro. Per questo caso qui, non mi sembra critico se uno ogni N salta.

> * Problema 2: Quando non ci sono nuovi PDF da scaricare mando un exit(1) da Python. Questo però [fa fallire l'intero job](https://github.com/gabacode/dasoe_updates/runs/4415812921?check_suite_focus=true#step:5:7), e manda notifica via email. Esiste un modo di terminare lo step in maniera piu graziosa? Ho provato con environment variables ma essendo python un processo fork non escono dallo script. Anche `if: failed()` termina il workflow in maniera scorbutica. Probabilmente qualche magia in bash potrebbe risolvere il problema? :)

Non ho guardato lo script. Ma invece di uscire, perché non devi il "flusso"?
In ogni caso non ti dovrebbe bloccare l'action, ma soltanto quello script da cui sei uscito.

Ma sopratutto, se fallisce il job, cosa perdi? Cosa vorresti ottenere, che il fallimento del job non ti fa ottenere?

> * Alternativa eco-friendly: Fetchare e convertire i files da un server esterno (come già succede col [bot telegram](https://github.com/gabacode/vaxExtract), che eventualmente manda un push al repo tramite deploy keys (ma potrebbe essere discutibile a livello di sicurezza). Ma sarebbe davvero eco-friendly? Quanto potrebbe impattare ad esempio confrontando l'installazione di tutte le dipendenze da una singola action ogni n minuti (con JAVA e quant'altro), invece?

Mi sembra una complicazione in più.

Grazie

**Comment by gabacode** [comment]
Grazie mille @aborruso!

Ho fatto alcune modifiche e adesso il workflow non fallisce se non trova un nuovo pdf, ma [salta lo step](https://github.com/gabacode/dasoe_updates/runs/4427573455?check_suite_focus=true#step:4:6) di conversione. Era un pò antipatico ricevere la notifica via mail ogni 15 minuti. Adesso printa semplicemente del testo, e in base a [quel testo](https://github.com/gabacode/dasoe_updates/blob/3548ace5bcb1f207c657c18c17145dd1a82fa20f/.github/workflows/main.yml#L27) il secondo step parte o meno.

Per preservare l'integrità dei .csv ho messo un [check](https://github.com/gabacode/dasoe_updates/blob/3548ace5bcb1f207c657c18c17145dd1a82fa20f/scripts/convert.py#L157) alla fine della conversione, ma in caso di errori di conversione il workflow dovrebbe fallire comunque, per evitare di pushare files errati.

Se per voi va bene sposto gli scripts e il workflow su questo repo.

**Comment by aborruso** [comment]
> Se per voi va bene sposto gli scripts e il workflow su questo repo.

Grazie!

**Comment by dennisangemi** [comment]
> Se per voi va bene sposto gli scripts e il workflow su questo repo.

Come potrebbe non andare bene!? Grazie mille @gabacode . Adesso c'è da sperare che non cambino il formato del bollettino

**Comment by dennisangemi** [comment]
@gabacode hai fatto un lavoro magnifico. Grazie mille. Io direi di chiudere questa issue al prossimo aggiornamento così da appurare il corretto funzionamento dello script. 

p.s.
Lo script che aggiorna i dati potrebbe anche essere in grado di modificare il [readme](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/README.md) per inserire il link del nuovo bollettino nella sezione [bollettini pubblicati](https://github.com/opendatasicilia/covid-open-report-sicilia/blob/main/README.md#bollettini-pubblicati)? Se non si può fare o è una cosa per la quale si perde tanto tempo lascia stare. Non so nemmeno se la sezione _bollettini pubblicati_ è nella posizione giusta: conviene spostarla?

**Comment by gabacode** [comment]
> Lo script che aggiorna i dati potrebbe anche essere in grado di modificare il readme per inserire il link del nuovo bollettino nella sezione bollettini pubblicati?

Grazie @dennisangemi , mi ero totalmente dimenticato del readme! Ho aggiunto una funzione con tale scopo in 1769eea4882d5e18f024d00f908680a89e525750. Dovrebbe funzionare finchè il titolo della porzione del file include la stringa `Bollettini pubblicati`, eventualmente si può modificare se decidiamo di cambiare il formato.

> Io direi di chiudere questa issue al prossimo aggiornamento così da appurare il corretto funzionamento dello script.

Sono d'accordo, revisioniamo il funzionamento del tutto al prossimo run 🤞

**Comment by dennisangemi** [comment]
Grazie a te!

**Comment by gabacode** [comment]
Aggiornamento: l'auto-update ha funzionato, ma ho dovuto modificare la keyword in 2a5cc00f01128d09c5ef4a052122ee489e253f83

**Comment by dennisangemi** [comment]
Grazie mille @gabacode ,  fantastico! se pensi che tutto sia ok possiamo anche chiudere questa issue

**Comment by gabacode** [comment]
Si, credo che possiamo chiudere. L'automatismo c'è, continueremo ad adattarlo dove e se necessario.
